server:
  port: 8080
spring:
  application:
    name: agile_es_springboot_data_elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9201
      cluster-name: my-elasticsearch
  elasticsearch:
    rest:
      uris: localhost:9200